spring:
  application:
    name: jwt-auth-learning
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    org.springframework: INFO

jwt:
  secret: ultraSecret
  issuer: jwt-auth-learning